version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: thursday
      time: "12:30"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: thursday
      time: "12:30"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
