version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
    time: "19:00"
  open-pull-requests-limit: 99
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: chromedriver-helper
    versions:
    - "> 2.1.0"
  - dependency-name: rubocop
    versions:
    - 1.11.0
    - 1.12.0
    - 1.9.0
  - dependency-name: listen
    versions:
    - 3.5.0
    - 3.5.1
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.2
    - 1.7.3
  - dependency-name: rails
    versions:
    - 6.1.2.1
    - 6.1.3.1
  - dependency-name: rspec-rails
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: amazing_print
    versions:
    - 1.3.0
  - dependency-name: rubocop-performance
    versions:
    - 1.10.1
  - dependency-name: webdrivers
    versions:
    - 4.6.0
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: simple_form
    versions:
    - 5.1.0
  - dependency-name: capybara
    versions:
    - 3.35.1
  - dependency-name: shoulda-matchers
    versions:
    - 4.5.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
    time: "19:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.9.1
  - dependency-name: "@rails/ujs"
    versions:
    - 6.1.2
  - dependency-name: "@rails/actioncable"
    versions:
    - 6.1.2
